version: "3.5"
services:
    dist-apriori-websrv:
        image: dist-apriori-websrv
        ports:
            - "8080:80"
        networks:
            - dist-apriori-net
    dist-apriori-miner:
        image: dist-apriori-miner
        entrypoint: ["/usr/sbin/sshd", "-D"]
        networks:
            - dist-apriori-net
networks:
    dist-apriori-net: