info:
  contact:
    email: edzhurov@uni-sofia.bg
    name: Evgeniy Dzhurov
  description: Master's diploma project in Distributed Systems and Mobile Technologies
    at FMI Sofia University, 2021
  title: Distributed System for Apriori Data Mining
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Show the dashboard
      tags:
      - dashboard
  /data:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      summary: List csv data
      tags:
      - data
    post:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Upload csv data
      tags:
      - data
  /data/{id}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Delete existing csv data
      tags:
      - data
    get:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Show specific csv data
      tags:
      - data
  /tasks:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      summary: List existing tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Add new task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Delete existing task
      tags:
      - tasks
    get:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Show specific task
      tags:
      - tasks
  /workers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      summary: List existing workers
      tags:
      - workers
    post:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Create worker
      tags:
      - workers
  /workers/{id}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Delete existing worker
      tags:
      - workers
    get:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Show specific worker
      tags:
      - workers
swagger: "2.0"
