info:
  contact:
    email: edzhurov@uni-sofia.bg
    name: Evgeniy Dzhurov
  description: This is a master's diploma project in Distributed Systems and Mobile
    Technologies at FMI Sofia University
  title: Distributed Apriori API
  version: "1.0"
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: Show an account
      tags:
      - accounts
swagger: "2.0"
